import os
import dotenv
from typing import Dict, Any

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from google.adk.agents import SequentialAgent, Agent

from agents.prioritizer import prioritizerAgent
from agents.harvester import harvesterAgent
from agents.classifier import classifierAgent

dotenv.load_dotenv()

localIssueAnalyser = SequentialAgent(
    name="Local Issue Analyser",
    description="A multi-stage AI pipeline for analyzing public sentiment and reports related to local community issues (e.g., infrastructure, services, safety). It processes raw data, classifies unique issues, and delivers a final, ranked priority report.",
    sub_agents=[harvesterAgent, classifierAgent, prioritizerAgent],
    instruction="""
    Execute the following three-step workflow:
    1. **Harvest:** Use the Harvester Agent to search and aggregate the most relevant, recent information and reports based on the user's input query.
    2. **Classify:** Use the Classifier Agent to structure and categorize the raw data into distinct local issues, assigning an estimated severity and frequency to each.
    3. **Prioritize:** Use the Prioritizer Agent to apply policy weights, calculate a final priority score for each issue, and output a concise, actionable report listing the Top 5 most urgent issues.

    Ensure the final response to the user is the executive summary generated by the Prioritizer Agent.
    """
)

app = FastAPI(
    title="Local Issue Analyser API",
    description="API for running the multi-agent system to prioritize local community concerns."
)

class AnalysisRequest(BaseModel):
    prompt: str

@app.post("/analyze", response_model=Dict[str, Any])
async def analyze_local_issues(request: AnalysisRequest):
    """
    Runs the SequentialAgent pipeline to analyze, classify, and prioritize issues 
    based on the provided prompt.
    """
    prompt = request.prompt
    
    if not prompt:
        raise HTTPException(status_code=400, detail="Prompt cannot be empty.")

    try:
        final_report = await localIssueAnalyser.run(prompt)
        
        return {
            "status": "success",
            "prompt": prompt,
            "report": final_report
        }

    except Exception as e:
        print(f"Error during agent run: {e}")
        raise HTTPException(status_code=500, detail=f"An error occurred during analysis: {e}")

@app.get("/")
def health_check():
    return {"message": "Local Issue Analyser API is running."}